import { EUserStatus, EGender, EChatStatus, EMessageType, EPrivacyVisibilityRange, EGroupMemberType, EMessageSendResult, EFileType } from '../../models';
// test not passing: tests might not match: model generated by default using texts, but backend will serve int.
describe('Enum Types', () => {
  test('should have correct EUserStatus values', () => {
    expect(EUserStatus.Online).toBe('Online');
    expect(EUserStatus.Offline).toBe('Offline');
    expect(EUserStatus.Quit).toBe('Quit');
    expect(EUserStatus.Disabled).toBe('Disabled');
    expect(EUserStatus.Unknown).toBe('Unknown');
    expect(EUserStatus.New).toBe('New');
  });

  test('EGender should have correct values', () => {
    expect(EGender.Male).toBe('Male');
    expect(EGender.Female).toBe('Female');
    expect(EGender.Unset).toBe('Unset');
  });

  test('EChatStatus should have correct values', () => {
    expect(EChatStatus.Normal).toBe('Normal');
    expect(EChatStatus.GroupDisabled).toBe('GroupDisabled');
    expect(EChatStatus.Unreachable).toBe('Unreachable');
  });

  test('EGroupMemberType should have correct values', () => {
    expect(EGroupMemberType.Owner).toBe('Owner');
    expect(EGroupMemberType.Admin).toBe('Admin');
    expect(EGroupMemberType.Member).toBe('Member');
  });

  test('EFileType should have correct values', () => {
    expect(EFileType.Image).toBe('Image');
    expect(EFileType.Video).toBe('Video');
    expect(EFileType.Audio).toBe('Audio');
    expect(EFileType.Document).toBe('Document');
    expect(EFileType.Other).toBe('Other');
  });
});