import { EUserStatus, EGender, EChatStatus, EMessageType, EPrivacyVisibilityRange, EGroupMemberType, EMessageSendResult, EFileType } from '../../models';
// test not passing: tests might not match: model generated by default using texts, but backend will serve int.
describe('Enum Types', () => {
  test('EUserStatus should have correct values', () => {
    expect(EUserStatus.Online).toBe(0);
    expect(EUserStatus.Offline).toBe(1);
    expect(EUserStatus.Quit).toBe(2);
    expect(EUserStatus.Disabled).toBe(3);
    expect(EUserStatus.New).toBe(4);
    expect(EUserStatus.Unknown).toBe(5);
  });

  test('EGender should have correct values', () => {
    expect(EGender.Male).toBe(0);
    expect(EGender.Female).toBe(1);
    expect(EGender.Unset).toBe(2);
  });

  test('EChatStatus should have correct values', () => {
    expect(EChatStatus.Normal).toBe(0);
    expect(EChatStatus.GroupDisabled).toBe(1);
    expect(EChatStatus.Unreachable).toBe(2);
  });

  test('EGroupMemberType should have correct values', () => {
    expect(EGroupMemberType.Owner).toBe(0);
    expect(EGroupMemberType.Admin).toBe(1);
    expect(EGroupMemberType.Member).toBe(2);
  });

  test('EFileType should have correct values', () => {
    expect(EFileType.Image).toBe(0);
    expect(EFileType.Video).toBe(1);
    expect(EFileType.Audio).toBe(2);
    expect(EFileType.Document).toBe(3);
    expect(EFileType.Other).toBe(4);
  });
});